services:
  mysql:
    image: mysql:8.0
    container_name: mysql_database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: devops
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: nuxt_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    container_name: express_backend
    ports:
      - "3001:3000"
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
    command: node index.js
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=devops
      - DB_PORT=3306
    depends_on:
      - mysql

volumes:
  db_data:
